language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install libaio1 # Needed to run mysqld for integration tests
script: mvn verify
# TODO: Need to add a deploy line when we have bintray access
# See: http://docs.travis-ci.com/user/customizing-the-build/
