language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install libaio1 # Needed to run mysqld for integration tests
script: mvn verify
# TODO: Add coveralls support
#after_success:
#  - mvn coveralls:report
cache:
  directories:
    - ~/.m2
branches:
  only:
    - master
    - /^elide-[0-9]+\.[0-9]+\.[0-9]+/
env:
  global:
    - secure: #TODO
    - secure: #TODO
