language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install libaio1 # Needed to run mysqld for integration tests
script: mvn verify
after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml
# TODO: Add coveralls support
#  - mvn coveralls:report
cache:
  directories:
    - ~/.m2
branches:
  only:
    - master
    - /^elide-parent-pom-[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/
env:
  global:
    - secure: #TODO
    - secure: #TODO
